// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vvEKhV4X4yWCLXhriishBU
// Component: _0O6g5SMsT_vH
import * as React from "react";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import { ThemeContext } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: Po2-1Vqdro6aE/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_todo_mvc.module.css"; // plasmic-import: vvEKhV4X4yWCLXhriishBU/projectcss
import * as sty from "./PlasmicHeader.module.css"; // plasmic-import: _0O6g5SMsT_vH/css

export const PlasmicHeader__VariantProps = new Array("state");

export const PlasmicHeader__ArgProps = new Array();

function PlasmicHeader__RenderFunc(props) {
  const { variants, args, overrides, forNode, onEnterTask } = props;
  const globalVariants = ensureGlobalVariants({
    theme: React.useContext(ThemeContext),
  });
  const [task, setTask] = React.useState("");

  const handleKeyDown = (e) => {
    if (e.key === "Enter") {
      onEnterTask(task);
      setTask("");
    }
  };

  const onInputChange = (e) => {
    setTask(e.target.value);
  };

  return (
    <div
      data-plasmic-name={"headerContainer"}
      data-plasmic-override={overrides.headerContainer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.root_reset,
        sty.headerContainer,
        {
          [sty.headerContainer__global_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),

          [sty.headerContainer__state_allChecked]: hasVariant(
            variants,
            "state",
            "allChecked"
          ),

          [sty.headerContainer__state_empty]: hasVariant(
            variants,
            "state",
            "empty"
          ),
        }
      )}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box, {
          [sty.box__state_empty]: hasVariant(variants, "state", "empty"),
        })}
      >
        {(hasVariant(variants, "state", "empty") ? false : true) ? (
          <img
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(defaultcss.img, sty.img, {
              [sty.img__global_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              ),

              [sty.img__state_allChecked]: hasVariant(
                variants,
                "state",
                "allChecked"
              ),

              [sty.img__state_empty]: hasVariant(variants, "state", "empty"),
            })}
            role={"img"}
            src={
              hasVariant(globalVariants, "theme", "dark")
                ? "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAxMiA2IiBoZWlnaHQ9IjYiIHdpZHRoPSIxMiIgc3R5bGU9ImZpbGw6IHJnYigyMTMsIDIwNiwgMjA2KTsiPgo8cGF0aCBmaWxsPSJibGFjayIgZD0iTTAuNjEyIDAuMTEyTDUuODQ0IDMuMjJMMTEuMDc2IDAuMTEyVjIuNUw1Ljg0NCA1LjUyNEwwLjYxMiAyLjQ4OFYwLjExMloiLz4KPC9zdmc+"
                : "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAxMiA2IiBoZWlnaHQ9IjYiIHdpZHRoPSIxMiI+CjxwYXRoIGZpbGw9ImJsYWNrIiBkPSJNMC42MTIgMC4xMTJMNS44NDQgMy4yMkwxMS4wNzYgMC4xMTJWMi41TDUuODQ0IDUuNTI0TDAuNjEyIDIuNDg4VjAuMTEyWiIvPgo8L3N2Zz4K"
            }
          />
        ) : null}
      </div>

      <input
        data-plasmic-name={"textbox"}
        data-plasmic-override={overrides.textbox}
        className={classNames(defaultcss.input, sty.textbox, {
          [sty.textbox__global_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),

          [sty.textbox__state_allChecked]: hasVariant(
            variants,
            "state",
            "allChecked"
          ),

          [sty.textbox__state_empty]: hasVariant(variants, "state", "empty"),
        })}
        placeholder={"What needs to be done?"}
        type={"text"}
        value={task}
        onChange={onInputChange}
        onKeyDown={handleKeyDown}
      />
    </div>
  );
}

const PlasmicDescendants = {
  headerContainer: ["headerContainer", "box", "img", "textbox"],
  box: ["box", "img"],
  img: ["img"],
  textbox: ["textbox"],
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeader__ArgProps,
      internalVariantPropNames: PlasmicHeader__VariantProps,
    });

    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      onEnterTask: props.onEnterTask,
      forNode: nodeName,
    });
  };
  if (nodeName === "headerContainer") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("headerContainer"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    img: makeNodeComponent("img"),
    textbox: makeNodeComponent("textbox"),
    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps,
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
